### ISSUE TITLE
Contribution guidelines question

### ISSUE THREAD

**Issue by CillianMyles** [Flutter-Bounty-Hunters/flutter_test_robots#6]
I have added this to one of our test files:

```dart
extension on WidgetTester {
  Future<void> pressCmdD() async {
    await sendKeyDownEvent(LogicalKeyboardKey.meta, platform: "macos");
    await sendKeyDownEvent(LogicalKeyboardKey.keyD, platform: "macos");
    await sendKeyUpEvent(LogicalKeyboardKey.keyD, platform: "macos");
    await sendKeyUpEvent(LogicalKeyboardKey.meta, platform: "macos");
    await pumpAndSettle();
  }
}
```

Would you like PRs submitted with this kind of logic? 

Anything to be aware of terms of contribution guidelines etc.?

**Comment by matthew-carroll** [comment]
If that's a common shortcut, you can add it to the existing API. But if it's a relatively uncommon shortcut, or rarely used, then I would probably recommend just defining that extension in your app, to avoid cluttering the `flutter_test_robots` API.
