### ISSUE TITLE
Ability to specify platform for keyboard events

### ISSUE THREAD

**Issue by CillianMyles** [Flutter-Bounty-Hunters/flutter_test_robots#8]
All of the keyboard interactions in `keyboard.dart` hard code platform as `'macos'`. 

Is there any plan to add the ability to support specifying other platforms? Even if not planned on your side, do you think this is this something that would make sense for the package?

**Comment by matthew-carroll** [comment]
I merged a change that now sets the platform based on the `defaultTargetPlatform`, which you can control in your tests. I also added a public override if you specifically want to set the platform for key events for a test without altering `defaultTargetPlatform`.

And I'm now realizing that I forgot to connect the override value to the chosen platform, so I'm going to file an issue for that and cut a new release.
